/*
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 *
 * Auto-generated by riscv-unified-db (udb-gen cfg-c-header)
 * Config: rv32i-core
 *
 * Define conventions:
 *   Extensions:           #define NAME_SUPPORTED and #define NAMEverPver_SUPPORTED
 *   Boolean params:       #define UDB_NAME           (present when true, absent when false)
 *   Integer params:       #define UDB_NAME value     and #define UDB_NAME_<value>
 *   Enum (string) params: #define UDB_NAME_VALUE     (value sanitized to uppercase identifier)
 *   Boolean arrays:       #define UDB_NAME_<index>   (one per true element)
 *   Integer arrays:       #define UDB_NAME_<value>   (one per unique element, sorted)
 *   String arrays:        #define UDB_NAME_<VALUE>   (one per unique element, sanitized)
 */

#ifndef UDB_CFG_RV32I_CORE_H
#define UDB_CFG_RV32I_CORE_H

/* Implemented extensions */
#define I_SUPPORTED
#define I2P1_SUPPORTED
#define SM_SUPPORTED
#define SM1P12P0_SUPPORTED

/* Configuration parameters */
#define UDB_CONFIG_PTR_ADDRESS 0
#define UDB_CONFIG_PTR_ADDRESS_0
#define UDB_MISALIGNED_LDST_EXCEPTION_PRIORITY_LOW
#define UDB_MTVAL_WIDTH 32
#define UDB_MTVAL_WIDTH_32
#define UDB_MTVEC_ACCESS_RW
#define UDB_MTVEC_BASE_ALIGNMENT_DIRECT 4
#define UDB_MTVEC_BASE_ALIGNMENT_DIRECT_4
#define UDB_MTVEC_ILLEGAL_WRITE_BEHAVIOR_RETAIN
#define UDB_MTVEC_MODES_0
#define UDB_MXLEN 32
#define UDB_MXLEN_32
#define UDB_M_MODE_ENDIANNESS_LITTLE
#define UDB_NUM_PMP_ENTRIES 0
#define UDB_NUM_PMP_ENTRIES_0
#define UDB_PHYS_ADDR_WIDTH 32
#define UDB_PHYS_ADDR_WIDTH_32
#define UDB_PMA_GRANULARITY 3
#define UDB_PMA_GRANULARITY_3
#define UDB_PRECISE_SYNCHRONOUS_EXCEPTIONS
#define UDB_TRAP_ON_EBREAK
#define UDB_TRAP_ON_ECALL_FROM_M
#define UDB_TRAP_ON_RESERVED_INSTRUCTION
#define UDB_TRAP_ON_UNIMPLEMENTED_CSR
#define UDB_TRAP_ON_UNIMPLEMENTED_INSTRUCTION
#define UDB_VENDOR_ID_BANK 0
#define UDB_VENDOR_ID_BANK_0
#define UDB_VENDOR_ID_OFFSET 0
#define UDB_VENDOR_ID_OFFSET_0

#endif /* UDB_CFG_RV32I_CORE_H */
